extends:
  - plugin:react/recommended
  - prettier/react
plugins:
  - eslint-plugin-react-hooks
settings:
  react:
    version: detect
rules:
  "@typescript-eslint/no-unused-vars": "off"
  react-hooks/exhaustive-deps: "error"
  react/display-name: "off"
  react/void-dom-elements-no-children: "warn"
