openapi: 3.0.2
info:
  title: Statshammer
  version: 1.0.0

paths:
  /status:
    get:
      operationId: getStatus
      summary: Get Status
      responses:
        200:
          $ref: "#/components/responses/StatusResponse"

  /api/modifiers:
    get:
      operationId: getModifiers
      summary: Fetch the list of modifiers for the weapon profiles and target
      responses:
        200:
          $ref: "#/components/responses/ModifiersResponse"

  /api/compare:
    post:
      operationId: getCompare
      summary: Compare the average damage outputs of the given units
      requestBody:
        $ref: "#/components/requestBodies/CompareBody"
      responses:
        200:
          $ref: "#/components/responses/CompareResponse"

components:
  requestBodies:
    CompareBody:
      content:
        application/json:
          schema:
            type: object
            properties:
              units:
                type: array
                items:
                  $ref: "#/components/schemas/Unit"

  responses:
    StatusResponse:
      description: Get the status of the server
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: string
              version:
                type: string
            required:
              - status
              - version

    ModifiersResponse:
      description: The Returned list of available modifiers
      content:
        application/json:
          schema:
            type: object
            properties:
              modifiers:
                type: array
                items:
                  $ref: "#/components/schemas/ModifierDefinition"
              target_modifiers:
                type: array
                items:
                  $ref: "#/components/schemas/ModifierDefinition"
            required:
              - modifiers
              - target_modifiers

    CompareResponse:
      description: Compare the average damage outputs of the given units
      content:
        application/json:
          schema:
            type: object
            properties:
              units:
                type: object
                additionalProperties:
                  type: string
              results:
                type: array
                items:
                  $ref: "#/components/schemas/AverageDamageResult"
            required:
              - units
              - results

  schemas:
    Unit:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
          example: Unit 1
        weapon_profiles:
          type: array
          items:
            $ref: "#/components/schemas/WeaponProfile"
      required:
        - id
        - name
        - weapon_profiles

    WeaponProfile:
      type: object
      properties:
        num_models:
          type: integer
          example: 5
        attacks:
          anyOf:
            - type: integer
            - type: string
          example: 2
        to_hit:
          type: integer
          example: 3
        to_wound:
          type: integer
          example: 4
        rend:
          type: integer
          example: 0
        damage:
          anyOf:
            - type: integer
            - type: string
          example: 1
        modifiers:
          type: array
          items:
            $ref: "#/components/schemas/Modifier"
      required:
        - num_models
        - attacks
        - to_hit
        - to_wound
        - rend
        - damage

    Modifier:
      type: object
      properties:
        id:
          type: string
          example: REROLL_ONES
        options:
          type: object
          properties:
            characteristic:
              type: string
              example: to_hit
      required:
        - id
        - options

    ModifierDefinition:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        options:
          type: object
          additionalProperties:
            $ref: "#/components/schemas/ModifierDefinitionOption"
      required:
        - id
        - name
        - description
        - options

    ModifierDefinitionOption:
      oneOf:
        - $ref: "#/components/schemas/ChoiceOption"
        - $ref: "#/components/schemas/NumberOption"
        - $ref: "#/components/schemas/RollOption"
        - $ref: "#/components/schemas/BooleanOption"
      discriminator:
        propertyName: type

    ChoiceOption:
      type: object
      properties:
        type:
          type: string
          enum:
            - choice
        items:
          type: array
          items:
            type: string
        default:
          type: string
      required:
        - type
        - items

    NumberOption:
      type: object
      properties:
        type:
          type: string
          enum:
            - number
        allow_dice:
          type: boolean
        default:
          type: number
      required:
        - type

    RollOption:
      type: object
      properties:
        type:
          type: string
          enum:
            - roll
        allow_ones:
          type: boolean
        default:
          type: number
      required:
        - type

    BooleanOption:
      type: object
      properties:
        type:
          type: string
          enum:
            - boolean
        default:
          type: boolean
      required:
        - type

    AverageDamageResult:
      type: object
      additionalProperties:
        type: number
